imageai/urls.py
from django.urls import path
from . import views

app_name="imageai"
urlpatterns=[
    path("",views.index,name="index"),
    path("predict/",views.predict,name="predict"),
]

imageapps/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
#imageaiの中のurls.pyをルーティングに組み込む
    path("imageai/",include("imageai.urls")),
]

imageai/models.py
from django.db import models
import numpy as np
import keras,sys
import tensorflow as tf
from keras.models import load_model
from PIL import Image
import io,base64

import os
import sys
import numpy as np
from tensorflow.keras.preprocessing.image import array_to_img, img_to_array, load_img, ImageDataGenerator
from tensorflow.keras.applications.efficientnet import preprocess_input, decode_predictions
import tensorflow as tf
import time
# Create your models here.
'''
#graph=tf.get_default_graph()
graph = tf.compat.v1.get_default_graph 
class Photo(models.Model):
    image=models.ImageField(upload_to="photos")

    IMAGE_SIZE=100#画像サイズ
    MODEL_PATH="./imageai/ml_models/model-1.h5"
    #imagename=[自分で作ったデータラベル]
    imagename=['test']
    image_len=len(imagename)

    def predict(self):
        model=None
        global graph#毎回同じモデルのセッションに投入して推論可能にする。
        with graph.as_default():
            model=load_model(self.MODEL_PATH)

            img_data=self.image.read()
            img_bin=io.BytesIO(img_data)

            image=Image.open(img_bin)
            image=image.convert("RGB")
            image=image.resize((self.IMAGE_SIZE,self.IMAGE_SIZE))
            data=np.asarray(image)/255.0
            X=[]
            X.append(data)
            X=np.array(X)

            result=model.predict([X])[0]
            predicted=result.argmax()
            percentage=int(result[predicted]*100)

            return self.imagename[predicted],percentage
    def image_src(self):
        with self.image.open() as img:
            base64_img=base64.b64encode(img.read()).decode()

            return "data:"+img.file.content_type+";base64,"+base64_img
'''
class Photo(models.Model):
    image=models.ImageField(upload_to="photos")
    print('image:{}'.format(image))
    imagename=['test']

    def predict(self):
        model = tf.keras.applications.EfficientNetB0(weights='imagenet')

        width = 224
        height = 224

        img_data=self.image.read()
        img_bin=io.BytesIO(img_data)
        image=Image.open(img_bin)
        image=image.convert("RGB")
        image=image.resize((width,height))
        data=np.asarray(image)/255.0
        X=[]
        X.append(data)
        X=np.array(X)

        y = model.predict(X)
    
        yy = decode_predictions(y, top=1)
       
        yyy = yy[0][0]
      
        return yyy[1],int(yyy[2]*100)

    def image_src(self):
        with self.image.open() as img:
            base64_img=base64.b64encode(img.read()).decode()

            return "data:"+img.file.content_type+";base64,"+base64_img

imageai/forms.py
from django import forms

class PhotoForm(forms.Form):
    image=forms.ImageField(widget=forms.FileInput(attrs={"class":"custom-file-input"}))

imageai/views.py
from django.http import HttpResponse
from django.template import loader
from .forms import PhotoForm
from .models import Photo
from django.shortcuts import redirect

def index(request):
    template=loader.get_template("imageai/index.html")
    context={"form":PhotoForm()}
    return HttpResponse(template.render(context,request))

def predict(request):
    if not request.method=="POST":
        return redirect("imageai:index")
    form=PhotoForm(request.POST,request.FILES)
    if not form.is_valid():
        raise ValueError("Formが不正です")

    photo=Photo(image=form.cleaned_data["image"])
    predicted,percentage=photo.predict()

    template=loader.get_template("imageai/result.html")

    context={
        "photo_name":photo.image.name,
        "photo_data":photo.image_src(),
        "predicted":predicted,
        "percentage":percentage,
    }
    return HttpResponse(template.render(context,request))

imageai/templates/imageai/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  {% load bootstrap4 %}
  {% bootstrap_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  {% bootstrap_javascript jquery="full" %}
  <title>画像推定サイト {% block title %}{% endblock %}</title>
</head>
hrefでstatic/css/style.cssを参照できる(setting.pyのSTATICFILES_URL)
<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Features</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
          <div class="title-method">
            <p class="navber-brand">画像判定アプリケーション</p>
          </div>
        </ul>
      </div>
    </nav>
  </header>
  <div class="container">
    {% block content %}{% endblock %}
  </div>
</body>
</html>

imageai/templates/imageai/index.html

{% extends "imageai/base.html" %}
{% block title %}画像判定アプリケーション{% endblock %}

{% block content %}
<div class="alert">
    <td><h1 class="mt-4 mb-5 boder-top">画像推定フォーム</h1></td>
  <br>
  <p class="custom-class">画像ファイルを選択して推定ボタンを押してください。</p>
  <br>
  <form action="{% url 'imageai:predict' %}"  method="post" class="form" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <div class="custom-file">
      {{ form.image }}
      <label class="custom-file-label" for="customFile">
        推定したいファイルを選択してください。
      </label>
    </div>
  </div>
  <br>
  <div class="btn-wrapper">
  <button type="submit" class="btn btn-secondary btn-lg btn-block">推定スタート!</button>
  </div>
  </form>
</div>
<br></br>

{% endblock %}

imageai/templates/imageai/result.html
{% extends "imageai/base.html" %}
{% block title %}ゴリラ・サル・チンパンジー推定結果{% endblock %}

{% block content %}
<div class="result">
  <h4 class="mt-4 mb-5 boder-bottom">画像推定結果</h4>
  <table class="table">
      <p class="body-wrapper">ファイル名:{{photo_name}}</p>

      <h2>画像ファイル<h2>
      <img class="preview-img" src={{photo_data}}></img>

      <p>動物名:{{predicted}}</p>
      <p>推定確率:{{percentage}} %</p>

  </table>
  <br>

  <a href="{% url 'imageai:index' %}" class="btn btn-primary btn-lg btn-block">選択メニューに戻る</a>

</div>
{% endblock %}